name: Build

on:
  push:
    branches: [ develop ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  COMPILER_IMAGE: stashapp/compiler:5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Upload release and checksum
      env:
        gjaw_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export stash_tag=v0.12.0
        pip3 install githubrelease
        pip3 install click==7.1.2
        githubrelease --github-token $gjaw_token --progress release growtopiajaw/stash create $stash_tag main.go
